name: medimate
description: A Week 2 UI prototype for MediMate (Teal theme) - semi-functional Flutter app.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.0
  uuid: ^4.3.3
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  

flutter:
  uses-material-design: true
  assets:
    - assets/medicine_data.json
    - assets/images/